
package com.test.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirstService", targetNamespace = "http://service.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirstService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://service.test.com/", className = "com.test.service.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://service.test.com/", className = "com.test.service.PrintResponse")
    public String print();

}
